With the following code example, we read each file row and split with "," each item of the row and put each one in a list. In total, we create 20 list. because there are 20 items in each row

In [1]:
import csv
from collections import defaultdict
columns = defaultdict(list)
with open('C:...input\\data.csv', 'r') as f:
    reader = csv.reader(f, delimiter=',')
    for row in reader:
        for i in row:
            sample_data =i.split(',')
            
            for j in range(len(sample_data)):
                columns[j].append(sample_data[j])

Second, we convert the dictionary created in the previous step into a data frame

In [2]:
data = {'Episode': columns.get(1), 'Station': columns.get(2),'Channel Type': columns.get(3), 'Season': columns.get(4),'Year': columns.get(5), 'Date': columns.get(6),'Day of week': columns.get(7), 'Start_time': columns.get(8),'End_time': columns.get(9), 'Length': columns.get(10),'Name of show': columns.get(11), 'Name of episode': columns.get(12),'Genre': columns.get(13), 'First time or rerun': columns.get(14),'# of episode in the season': columns.get(15), 'Movie?': columns.get(16),'Game of the Canadiens during episode?': columns.get(17),'Market Share_total': columns.get(18),'Temperature in Montreal during episode': columns.get(19)}

In [3]:
import pandas as pd
dataset =pd.DataFrame.from_dict(data,orient='index')

Since the target column contains non-number irrelevant values, we have converted the values to null values with the following code example

In [4]:
df =dataset.transpose()
df['Market Share_total'] = df['Market Share_total'].str.replace(r'\D', '')
df

,Episode,Station,Channel Type,Season,Year,Date,Day of week,Start_time,End_time,Length,Name of show,Name of episode,Genre,First time or rerun,# of episode in the season,Movie?,Game of the Canadiens during episode?,Market Share_total,Temperature in Montreal during episode
0,"""Episode""","""Station""","""Channel Type""","""Season""","""Year""","""Date""","""Day of week""","""Start_time""","""End_time""","""Length""","""Name of show""","""Name of episode""","""Genre""","""First time or rerun""","""# of episode in the season""","""Movie?""","""Game of the Canadiens during episode?""",,"""Temperature in Montreal during episode"";"
1,"""Vidأ©oclips V""","""V Total""","""General Channel""","""Fall""","""2016""",2016-08-29,"""Monday""",2016-08-29 06:00:00,2016-08-29 08:00:00,"""8""","""Vidأ©oclips V""",NA,"""Music Video Clips""","""No""","""Yes""","""No""","""No""",09,20.4;
2,"""Apollo dans l'frigo""","""V Total""","""General Channel""","""Fall""","""2016""",2016-08-29,"""Monday""",2016-08-29 08:00:00,2016-08-29 08:30:00,"""2""","""Apollo dans l'frigo""",NA,"""Informal Education and Recreation and Leisure""","""No""","""Yes""","""No""","""No""",05,19.125;
3,"""Infopublicitأ©""","""V Total""","""General Channel""","""Fall""","""2016""",2016-08-29,"""Monday""",2016-08-29 08:30:00,2016-08-29 09:00:00,"""2""","""Infopublicitأ©""",NA,"""Infomercials","Promotional and Corporate Videos""","""No""","""Yes""","""No""",,0.3
4,"""Infos","Les""","""V Total""","""General Channel""","""Fall""","""2016""",2016-08-29,"""Monday""",2016-08-29 09:00:00,2016-08-29 10:00:00,"""4""","""Infos","Les""",NA,"""News""","""No""","""Yes""",,"""No"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616652,"""Backstage : Les coulisses du succأ¨s""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 08:00:00,2019-01-22 08:30:00,"""2""","""Backstage : Les coulisses du succأ¨s""","""Tous en choeur""",None,None,None,None,None,None,None
616653,"""Le Studio""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 08:30:00,2019-01-22 09:00:00,"""2""","""Le Studio""","""On tourne et on tourne""",None,None,None,None,None,None,None
616654,"""Jane l'Immaculأ©e (M)""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 09:00:00,2019-01-22 10:00:00,"""4""","""Jane l'Immaculأ©e (M)""","""L'effet d'une bombe""",None,None,None,None,None,None,None
616655,"""Jane l'Immaculأ©e (M)""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 10:00:00,2019-01-22 11:00:00,"""4""","""Jane l'Immaculأ©e (M)""","""Nouvelle donne""",None,None,None,None,None,None,None
616656,"""Mom V.F. (M)""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 11:00:00,2019-01-22 11:30:00,"""2""","""Mom V.F. (M)""","""Les bons samaritains""",None,None,None,None,None,None,None

We will then remove the null values created in the previous step

In [5]:
df = df[df['Market Share_total'].str.strip().astype(bool)]

Since our classification algorithm is executed with numeric values, we have encoded all non-numeric values into unique numbers in the following code example

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df = df.apply(lambda col: le.fit_transform(col.astype(str)), axis=0, result_type='expand')
df

,Episode,Station,Channel Type,Season,Year,Date,Day of week,Start_time,End_time,Length,Name of show,Name of episode,Genre,First time or rerun,# of episode in the season,Movie?,Game of the Canadiens during episode?,Market Share_total,Temperature in Montreal during episode
1,5884,186,17,3,0,7,4,42,47,30,5526,71018,12,2,3,2,2,9,7792
2,223,186,17,3,0,7,4,56,50,12,209,71018,9,2,3,2,2,5,7144
6,3155,186,17,3,0,7,4,74,67,12,2907,71018,20,2,3,2,2,182,6900
7,5611,186,17,3,0,7,4,77,70,12,5264,71018,7,2,3,2,2,142,7193
8,3693,186,17,3,0,7,4,80,77,26,3401,71018,17,2,3,2,2,51,7257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616633,2296,166,25,13,3,883,8,117725,118547,12,2114,33544,17,2,3,2,2,0,2452
616634,1195,166,25,13,3,883,8,117726,118550,12,1092,70239,17,2,3,2,2,21,2452
616635,1195,166,25,13,3,883,8,117729,118551,12,1092,67737,16,2,3,2,2,3,2462
616636,1062,166,25,13,3,883,8,117731,118555,26,969,68801,16,2,3,2,2,4,2481
616637,6147,166,25,13,3,883,8,117734,118557,26,5777,68471,16,2,3,2,2,71,2462

Since the classes in the target column are unbalanced, with the sample code below we have selected 50 samples from each class we have 500 different classes that will be created in the dataframe with 25000 rows. There are different ways to balance classes, for example, smote, but since the dataset is large, if you use one of these methods you will need a lot of RAM to process

In [7]:
balanced_df=df.groupby('Market Share_total',as_index = False,group_keys=False).apply(lambda s: s.sample(50,replace=True))
balanced_df

,Episode,Station,Channel Type,Season,Year,Date,Day of week,Start_time,End_time,Length,Name of show,Name of episode,Genre,First time or rerun,# of episode in the season,Movie?,Game of the Canadiens during episode?,Market Share_total,Temperature in Montreal during episode
234107,6118,185,25,8,1,345,9,43143,42677,26,5750,45512,7,2,3,2,2,0,8434
394023,1060,169,25,13,2,569,9,74200,74093,26,967,43504,23,2,3,2,2,0,245
267385,2263,167,25,3,1,393,8,49707,49312,26,2084,68306,9,2,3,2,2,0,7153
554977,2610,167,25,3,2,795,3,105718,106196,12,2416,69962,9,2,3,2,2,0,4287
178054,5944,185,25,7,1,264,5,33096,32439,12,5584,59827,8,2,3,2,2,0,11569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,2180,183,17,3,0,9,9,288,281,1,2004,71018,21,2,3,2,2,499,7928
337276,5771,179,17,13,2,492,9,63631,63342,12,5418,66310,3,3,3,2,3,499,1934
38418,403,181,25,3,0,63,4,7482,7216,21,366,71018,11,2,3,2,2,499,10644
135364,3052,27,22,6,8,0,79,1,24704,2063,35,46744,17,2,3,2,2,499,1161
357763,5232,179,17,13,2,521,7,67515,67314,1,4918,2936,4,2,3,2,2,499,11569

Next we select the column 'Market Share_total' as the target column

In [8]:
df_feature=balanced_df.loc[:, balanced_df.columns != 'Market Share_total'].values
df_labels =  balanced_df['Market Share_total'].values

Here we use the chi2 method to Feature Selection

In [15]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_selector = SelectKBest(chi2, k=10)
X_kbest = chi2_selector.fit_transform(df_feature, df_labels)
print(chi2_selector.scores_)

[4.36507336e+06 2.03648424e+04 7.76382157e+03 1.09028919e+04
 3.50811484e+03 6.32139123e+05 1.11901403e+06 8.76840645e+07
 7.70981233e+07 3.96233237e+07 4.64406571e+06 4.53007892e+07
 1.33880658e+04 4.99379496e+01 6.72119046e+01 1.04936456e+02
 2.78218593e+02 7.08218394e+06]

In [9]:
df_feature2 = balanced_df.iloc [:, [0,2,5,7,8,10,11,16]]

We then split the data into test and training sets

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_feature2,  df_labels, test_size = 0.2, random_state = 0)

We use the random forest algorithm for prediction

In [11]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0).fit(X_train,  y_train)

In [12]:
Y_pred_rf = clf.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
score_rf = round(accuracy_score(Y_pred_rf,y_test)*100,2)

print("The accuracy score achieved using RandomForestClassifier is: "+str(score_rf)+" %")

The accuracy score achieved using Decision Tree is: 53.2 %

Finally, enter the test data and predict the target value for each of the samples using a random forest trained algorithm

In [29]:
import csv
from collections import defaultdict
columns = defaultdict(list)
with open('...input\\test.csv', 'r') as f:
    reader = csv.reader(f, delimiter=',')
    for row in reader:
        for i in row:
            sample_data =i.split(',')
            
            for j in range(len(sample_data)):
                columns[j].append(sample_data[j])

In [30]:
data = {'Episode': columns.get(1), 'Station': columns.get(2),'Channel Type': columns.get(3), 'Season': columns.get(4),'Year': columns.get(5), 'Date': columns.get(6),'Day of week': columns.get(7), 'Start_time': columns.get(8),'End_time': columns.get(9), 'Length': columns.get(10),'Name of show': columns.get(11), 'Name of episode': columns.get(12),'Genre': columns.get(13), 'First time or rerun': columns.get(14),'# of episode in the season': columns.get(15), 'Movie?': columns.get(16),'Game of the Canadiens during episode?': columns.get(17),'Temperature in Montreal during episode': columns.get(18)}

In [31]:
import pandas as pd
dataset_test =pd.DataFrame.from_dict(data,orient='index')

In [32]:
dataset_test =dataset_test.transpose()
dataset_test2 = dataset_test.drop(dataset_test.index[0])
dataset_test2

,Episode,Station,Channel Type,Season,Year,Date,Day of week,Start_time,End_time,Length,Name of show,Name of episode,Genre,First time or rerun,# of episode in the season,Movie?,Game of the Canadiens during episode?,Temperature in Montreal during episode
1,"""Mom V.F. (M)""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 11:30:00,2019-01-22 12:00:00,"""2""","""Mom V.F. (M)""","""Abstinence""","""Ongoing Comedy Series (Sitcoms)""","""No""","""Yes""","""No""","""No""",-22.525;
2,"""2 filles fauchأ©es""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 12:00:00,2019-01-22 12:30:00,"""2""","""2 filles fauchأ©es""","""Et la rupture""","""Ongoing Comedy Series (Sitcoms)""","""No""","""Yes""","""No""","""No""",-21.625;
3,"""The Big Bang Theory""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 12:30:00,2019-01-22 13:00:00,"""2""","""The Big Bang Theory""","""La dأ©sintأ©gration de la sonde spatiale""","""Ongoing Comedy Series (Sitcoms)""","""No""","""Yes""","""No""","""No""",-21.625;
4,"""Flashpoint""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 13:00:00,2019-01-22 14:00:00,"""4""","""Flashpoint""","""Retraite impossible (P)""","""Ongoing Dramatic Series""","""Yes""","""Yes""","""No""","""No""",-20.375;
5,"""Les Frأ¨res Scott""","""VRAK+""","""Specialty Channel""","""Winter""","""2019""",2019-01-22,"""Tuesday""",2019-01-22 14:00:00,2019-01-22 15:00:00,"""4""","""Les Frأ¨res Scott""","""Premiأ¨res dأ©sillusions""","""Ongoing Dramatic Series""","""No""","""Yes""","""No""","""No""",-19.1;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154161,"""Pour emporter""","""ARTV+""","""Specialty Channel""","""Summer""","""2019""",2019-08-25,"""Sunday""",2019-08-25 18:00:00,2019-08-25 19:00:00,"""4""","""Pour emporter""",NA,None,None,None,None,None,None
154162,"""Amour du country""","""ARTV+""","""Specialty Channel""","""Summer""","""2019""",2019-08-25,"""Sunday""",2019-08-25 19:00:00,2019-08-25 20:00:00,"""4""","""Amour du country""",NA,None,None,None,None,None,None
154163,"""Notre cinأ©ma""","""ARTV+""","""Specialty Channel""","""Summer""","""2019""",2019-08-25,"""Sunday""",2019-08-25 20:00:00,2019-08-25 21:30:00,"""6""","""Notre cinأ©ma""","""All you can eat Bouddha",None,None,None,None,None,None
154164,"""Cinأ©ma du vendredi (R)""","""ARTV+""","""Specialty Channel""","""Summer""","""2019""",2019-08-25,"""Sunday""",2019-08-25 21:30:00,2019-08-26 00:00:00,"""10""","""Cinأ©ma du vendredi (R)""","""Selma""",None,None,None,None,None,None
154165,"""Cinأ©ma #2""","""ARTV+""","""Specialty Channel""","""Summer""","""2019""",2019-08-25,"""Sunday""",2019-08-25 00:00:00,2019-08-25 02:00:00,"""8""","""Cinأ©ma #2""","""Une أ©ducation""",None,None,None,None,None,None

In [33]:

dataset_test2 = dataset_test2.apply(lambda col: le.fit_transform(col.astype(str)), axis=0, result_type='expand')
dataset_test2

,Episode,Station,Channel Type,Season,Year,Date,Day of week,Start_time,End_time,Length,Name of show,Name of episode,Genre,First time or rerun,# of episode in the season,Movie?,Game of the Canadiens during episode?,Temperature in Montreal during episode
1,1475,95,19,9,0,4,6,32,31,12,1380,6993,3029,1640,303,93,15,1083
2,15,95,19,9,0,4,6,33,32,12,19,12451,3029,1640,303,93,15,1079
3,2478,95,19,9,0,4,6,34,34,12,2341,16692,3029,1640,303,93,15,1079
4,705,95,19,9,0,4,6,36,35,30,665,26184,3030,2100,303,93,15,1068
5,1249,95,19,9,0,4,6,38,37,30,1172,25140,3030,1640,303,93,15,919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154161,1676,75,19,5,0,219,4,35540,36327,30,1558,33256,3117,2140,304,120,19,5475
154162,85,75,19,5,0,219,4,35544,36329,30,87,33256,3117,2140,304,120,19,5475
154163,1545,75,19,5,0,219,4,35546,36334,32,1443,7205,3117,2140,304,120,19,5475
154164,399,75,19,5,0,219,4,35551,36352,2,379,26979,3117,2140,304,120,19,5475
154165,393,75,19,5,0,219,4,35416,36207,34,373,29781,3117,2140,304,120,19,5475

In [34]:
dataset_test2 = dataset_test2.iloc [:, [0,2,5,7,8,10,11,16]]

In [35]:
Y_pred_test = clf.predict(dataset_test2)

In [36]:
print(Y_pred_test)

[ 96 161  96 ... 141 116 116]